package com.aerospace.aitt.flashing.service;

import com.aerospace.aitt.core.util.FileUtil;
import com.aerospace.aitt.flashing.model.FlashingSession;
import com.aerospace.aitt.flashing.model.SoftwareModule;
import com.aerospace.aitt.flashing.model.TargetProfile;

import java.io.IOException;
import java.nio.file.Path;
import java.time.format.DateTimeFormatter;
import java.time.ZoneId;

/**
 * Generates TRACE32 CMM scripts for flashing operations.
 */
public class CmmGenerator {
    
    private static final DateTimeFormatter TIMESTAMP_FORMAT = 
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());
    
    /**
     * Generates a complete CMM script for the flashing session.
     */
    public String generate(FlashingSession session) {
        StringBuilder sb = new StringBuilder();
        TargetProfile target = session.targetProfile();
        
        // Header comment
        appendHeader(sb, session);
        
        // System initialization
        appendSystemInit(sb, target);
        
        // Flash configuration
        appendFlashConfig(sb, target);
        
        // Flash each module
        for (int i = 0; i < session.modules().size(); i++) {
            SoftwareModule module = session.modules().get(i);
            appendModuleFlash(sb, module, i + 1, session.moduleCount());
        }
        
        // Verification section
        appendVerification(sb, session);
        
        // Footer
        appendFooter(sb);
        
        return sb.toString();
    }
    
    /**
     * Saves the generated script to a file.
     */
    public void saveTo(Path outputPath, String script) throws IOException {
        FileUtil.writeString(outputPath, script);
    }
    
    /**
     * Generates and saves in one step.
     */
    public void generateAndSave(FlashingSession session, Path outputPath) throws IOException {
        String script = generate(session);
        saveTo(outputPath, script);
    }
    
    private void appendHeader(StringBuilder sb, FlashingSession session) {
        sb.append("; ============================================================================\n");
        sb.append("; TRACE32 CMM Flash Script\n");
        sb.append("; Generated by: Automation Integration Test Tool (AITT)\n");
        sb.append("; Timestamp:    ").append(TIMESTAMP_FORMAT.format(session.timestamp())).append("\n");
        sb.append("; Target:       ").append(session.targetProfile().name()).append("\n");
        sb.append("; CPU:          ").append(session.targetProfile().cpuType()).append("\n");
        sb.append("; Modules:      ").append(session.moduleCount()).append("\n");
        sb.append("; Session ID:   ").append(session.id()).append("\n");
        sb.append("; ============================================================================\n");
        sb.append("\n");
    }
    
    private void appendSystemInit(StringBuilder sb, TargetProfile target) {
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("; System Initialization\n");
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("\n");
        sb.append("SYStem.RESet\n");
        sb.append("SYStem.CPU ").append(target.cpuType()).append("\n");
        sb.append("SYStem.CONFIG.DEBUGPORTTYPE JTAG\n");
        sb.append("SYStem.Up\n");
        sb.append("\n");
        sb.append("; Wait for system to stabilize\n");
        sb.append("WAIT 100.ms\n");
        sb.append("\n");
    }
    
    private void appendFlashConfig(StringBuilder sb, TargetProfile target) {
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("; Flash Configuration\n");
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("\n");
        sb.append("FLASH.RESet\n");
        sb.append("\n");
        sb.append("; Define flash region\n");
        sb.append(String.format("FLASH.Create 1. 0x%08X--0x%08X 0x1000 TARGET Long\n", 
            target.flashStart(), target.flashEnd() - 1));
        sb.append("\n");
        sb.append("; Set flash programming target RAM\n");
        sb.append(String.format("FLASH.TARGET 0x%08X 0x%08X 0x1000 ~~/demo/arm/flash/long/\n",
            target.ramAddress(), target.ramAddress() + 0x2000));
        sb.append("\n");
    }
    
    private void appendModuleFlash(StringBuilder sb, SoftwareModule module, int index, int total) {
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append(String.format("; Module %d/%d: %s\n", index, total, module.name()));
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("\n");
        
        sb.append(String.format("PRINT \"Flashing module %d/%d: %s\"\n", index, total, module.name()));
        sb.append(String.format("PRINT \"  File:    %s\"\n", module.fileName()));
        sb.append(String.format("PRINT \"  Address: %s\"\n", module.formattedAddress()));
        sb.append(String.format("PRINT \"  Size:    %s\"\n", module.formattedSize()));
        sb.append("\n");
        
        // Load binary data
        String filePath = module.filePath().toString().replace("\\", "/");
        String loadCommand = getLoadCommand(module, filePath);
        
        sb.append("; Load firmware data\n");
        sb.append(loadCommand).append("\n");
        sb.append("\n");
        
        // Program flash
        sb.append("; Program flash memory\n");
        sb.append("FLASH.ReProgram ALL\n");
        sb.append(loadCommand).append("\n");
        sb.append("FLASH.ReProgram OFF\n");
        sb.append("\n");
        
        sb.append(String.format("PRINT \"Module %d/%d flashed successfully\"\n", index, total));
        sb.append("\n");
    }
    
    private String getLoadCommand(SoftwareModule module, String filePath) {
        String ext = module.fileExtension().toLowerCase();
        
        return switch (ext) {
            case "bin" -> String.format("Data.LOAD.Binary \"%s\" 0x%08X", 
                filePath, module.flashAddress());
            case "hex" -> String.format("Data.LOAD.IntelHEX \"%s\"", filePath);
            case "elf" -> String.format("Data.LOAD.Elf \"%s\"", filePath);
            case "srec", "s19" -> String.format("Data.LOAD.S3Record \"%s\"", filePath);
            default -> String.format("Data.LOAD.Binary \"%s\" 0x%08X", 
                filePath, module.flashAddress());
        };
    }
    
    private void appendVerification(StringBuilder sb, FlashingSession session) {
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("; Verification\n");
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("\n");
        sb.append("PRINT \"Verifying flash contents...\"\n");
        sb.append("\n");
        
        for (SoftwareModule module : session.modules()) {
            String filePath = module.filePath().toString().replace("\\", "/");
            
            sb.append(String.format("; Verify %s\n", module.name()));
            
            if (module.fileExtension().equalsIgnoreCase("bin")) {
                sb.append(String.format("Data.LOAD.Binary \"%s\" 0x%08X /ComPare\n",
                    filePath, module.flashAddress()));
            } else {
                sb.append(String.format("Data.LOAD.Elf \"%s\" /ComPare\n", filePath));
            }
            
            sb.append("IF FOUND()\n");
            sb.append("(\n");
            sb.append(String.format("  PRINT \"ERROR: Verification failed for %s\"\n", module.name()));
            sb.append("  ENDDO\n");
            sb.append(")\n");
            sb.append(String.format("PRINT \"Verified: %s\"\n", module.name()));
            sb.append("\n");
        }
    }
    
    private void appendFooter(StringBuilder sb) {
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("; Completion\n");
        sb.append("; ---------------------------------------------------------------------------\n");
        sb.append("\n");
        sb.append("PRINT \"\"\n");
        sb.append("PRINT \"============================================\"\n");
        sb.append("PRINT \"  FLASHING COMPLETED SUCCESSFULLY\"\n");
        sb.append("PRINT \"============================================\"\n");
        sb.append("PRINT \"\"\n");
        sb.append("\n");
        sb.append("; Reset and run\n");
        sb.append("; SYStem.Up\n");
        sb.append("; Go\n");
        sb.append("\n");
        sb.append("ENDDO\n");
    }
}
